spring:
  application:
    name: api-gateway
server:
  port: 8040
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    user: # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**
      service-id: provider-user
  #ignored-services: provider-user  #忽略服务