---
spring:
  profiles: discovery
server:
  port: 8761
eureka:
  instance:
    hostname: discovery
  client:
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka

---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka