server:
  port: 8010
spring:
  application:
    name: consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      #defaultZone: http://discovery2:8762/eureka/, http://discovery1:8761/eureka/
    instance:
      preferIpAddress: true