---
spring:
  profiles: discovery1

server:
  port: 8761

eureka:
  instance:
    hostname: discovery1
  client:
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka/

---
spring:
  profiles: discovery2

server:
  port: 8762

eureka:
  instance:
    hostname: discovery2
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/