server:
  port: 8030
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        #git:
        #  uri: https://github.com/lorelib/springcloud-study.git
        #  search-paths: config-repo
        #  username:
        #  password:
        native:
          searchLocations: classpath:/config

# 获取git上的资源信息遵循如下规则：
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties