server:
  port: 8000
spring:
  application:
    name: provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: debug
    org.hibernate: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      #defaultZone: http://discovery2:8762/eureka/, http://discovery1:8761/eureka/